Link to googlesheets db
Loiklak/keskon-mange-ce-midi pull request #1
Opened 2024-05-06 09:21 UTC by corentingst

Move the restaurant database to the google sheet below and link the chooser to it.

https://docs.google.com/spreadsheets/d/1B1kD-kZQiJUEYcSmAXom_lY7_JhOLp9UTq0Uf44wNY0/edit#gid=0

2024-05-07 09:01 UTC, Loiklak commented on package.json
> +    "vercel": "^34.1.4"
Tu peux le mettre en devdeps plutôt stp ?

2024-05-07 09:01 UTC, Loiklak commented on src/app/page.tsx
>    >();
Clean l'ancien code si plus utilisé

2024-05-07 09:01 UTC, Loiklak commented on src/app/restaurant-list/page.tsx
>    const restaurants = await getAllRestaurants();
same si plus utilisé faut le clear

2024-05-07 09:01 UTC, Loiklak commented on src/app/restaurant-list/page.tsx
>    const restaurants = await getAllRestaurants();
En soi on n'a même plus besoin de cette page comme on a le google sheets maintenant donc tu peux la supprimer et remplacer le lien en bas de page par le lien google sheets

2024-05-07 09:01 UTC, Loiklak commented on src/core/restaurants/getAllRestaurantsSheets.tsx
> +const sheetsColumnsToTechnicalName = {
Tu peux mettre le nom en screaming case comme c'est une constante

2024-05-07 09:01 UTC, Loiklak commented on src/core/restaurants/getAllRestaurantsSheets.tsx
> +// Correct header type guard
Pourquoi tu as besoin de rajouter ce comm ici ?

2024-05-07 09:01 UTC, Loiklak commented on src/core/restaurants/getAllRestaurantsSheets.tsx
> +// Boolean key type guard
same ici, commentaire nécessaire ? Et pk ?

2024-05-07 09:01 UTC, Loiklak commented on src/core/restaurants/getAllRestaurantsSheets.tsx
> +const processBoolean = (value: string): boolean => {
```suggestion
const processSheetsBooleanCell = (value: string): boolean => {
```

Pour apporter un peu plus de contexte sur ce que tu process :)

2024-05-07 09:01 UTC, Loiklak commented on src/core/restaurants/getAllRestaurantsSheets.tsx
> +  else {throw new Error('Value is not in "TRUE" or "FALSE" format')}
Tu devrais rajouter dans ton erreur c'est quoi la valeur qui a été passée et qui n'est ni TRUE ni FALSE

Ca facilitera le debug

2024-05-07 09:01 UTC, Loiklak commented on src/core/restaurants/getAllRestaurantsSheets.tsx
> +const arrayToRestaurantInfos = (data: string[][]): RestaurantInfos[] => {
```suggestion
const gSheetsDtoToRestaurantInfos = (data: string[][]): RestaurantInfos[] => {
```

array c'est extrêmement générique on ne sait pas c'est quoi

2024-05-07 09:01 UTC, Loiklak commented on src/core/restaurants/getAllRestaurantsSheets.tsx
> +  }else{return []}
Tu veux throw là plutôt

2024-05-07 09:01 UTC, Loiklak commented on src/core/restaurants/getAllRestaurantsSheets.tsx
> +        // case disjunction: value = string or value = boolean
commentaire nécessaire? ;)

2024-05-07 09:01 UTC, Loiklak commented on src/core/restaurants/getAllRestaurantsSheets.tsx
> +  )
```suggestion
  const RestaurantsTable = await fetch(generateAPIURL(documentID, valuesRange, googleSheetsAPIKey), { headers: { accept: "application/json" }, cache: 'no-cache'}).json()
```

Il faut choisir soit utiliser des .then soit faire du async await

C'est bien d'utiliser async await en général car + lisible :)

2024-05-07 09:01 UTC, Loiklak commented on src/core/restaurants/getAllRestaurantsSheets.tsx
> +  const RestaurantsTable = await fetch(generateAPIURL(documentID, valuesRange, googleSheetsAPIKey), { headers: { accept: "application/json" }, cache: 'no-cache'}).then(
```suggestion
  const restaurantsTable = await fetch(generateAPIURL(documentID, valuesRange, googleSheetsAPIKey), { headers: { accept: "application/json" }, cache: 'no-cache'}).then(
```

Attention au casing ! Le standard en JS = variables en camelCase

2024-05-07 09:01 UTC, Loiklak commented on src/core/restaurants/getRandomRestaurantSheets.tsx
> +  }
```suggestion
  function isRestaurantInfoKey(key: any, restaurant: RestaurantInfos): key is CorrectKey {
    const expectedKeys = Object.keys(restaurant)
    return expectedKeys.includes(key)
  }
```

Naming > Comments ;)

2024-05-07 09:01 UTC, Loiklak commented on src/core/restaurants/getRandomRestaurantSheets.tsx
> +  const restaurantSatisfiesClause = (restaurant: RestaurantInfos, whereClause: any): Boolean => {
Pas de typage any ! C'est la porte ouverte aux bugs + ça aide pas les autres devs à savoir comment utiliser ta fonction

Définis un type comme ça on sait ce qu'on manipule

2024-05-07 09:01 UTC, Loiklak commented on src/core/restaurants/getRandomRestaurantSheets.tsx
> +      if (!isCorrectKey(key, restaurant) || (whereClause[key] !== undefined && restaurant[key] !== whereClause[key])) {
La condition est pas évidente à comprendre, tu pourrais la décomposer avec des variables pour expliciter le sens métier ?

2024-05-07 09:08 UTC, corentingst commented on package.json
> +    "vercel": "^34.1.4"
Okay

2024-05-07 12:18 UTC, corentingst commented on src/app/page.tsx
>    >();
Okay

2024-05-07 12:36 UTC, corentingst commented on src/app/restaurant-list/page.tsx
>    const restaurants = await getAllRestaurants();
Alors j'ai suppr la page tsx, mais comment être sur d'avoir supprimé l'occurence de la page dans tout le doc? par exemple dans le router?

2024-05-07 12:36 UTC, corentingst commented on src/core/restaurants/getAllRestaurantsSheets.tsx
> +const sheetsColumnsToTechnicalName = {
Tous les noms de constantes en screaming case?

2024-05-07 12:39 UTC, corentingst commented on src/core/restaurants/getAllRestaurantsSheets.tsx
> +const processBoolean = (value: string): boolean => {
Yes

2024-05-07 12:45 UTC, corentingst commented on src/core/restaurants/getAllRestaurantsSheets.tsx
> +  else {throw new Error('Value is not in "TRUE" or "FALSE" format')}
Okay

2024-05-07 12:46 UTC, corentingst commented on src/core/restaurants/getAllRestaurantsSheets.tsx
> +const arrayToRestaurantInfos = (data: string[][]): RestaurantInfos[] => {
done

2024-05-07 12:46 UTC, corentingst commented on src/core/restaurants/getAllRestaurantsSheets.tsx
> +  }else{return []}
Okay

2024-05-07 12:54 UTC, corentingst commented on src/core/restaurants/getAllRestaurantsSheets.tsx
> +  )
Avec un "await (await ...))", c'est bien ça?

2024-05-07 12:55 UTC, corentingst commented on src/core/restaurants/getRandomRestaurantSheets.tsx
> +  }
Okay

2024-05-10 15:28 UTC, greg-ab requested changes
Quelques remarques et pistes d'amélioration !

2024-05-10 15:28 UTC, greg-ab commented on package.json
>      "@types/react-dom": "18.2.7",
Normalement tous les types sont en devDeps

2024-05-10 15:28 UTC, greg-ab commented on src/app/layout.tsx
> +                  Sheets restaus
Pourquoi ne pas garder le wording de Liste ?

2024-05-10 15:28 UTC, greg-ab commented on src/app/page.tsx
> +    useState<RestaurantInfos | undefined>();
L'union de type avec undefined est faite automatiquement lorsque la méthode useState est appelée sans argument

2024-05-10 15:28 UTC, greg-ab commented on src/core/restaurants/getAllRestaurantsSheets.tsx
> +  const restaurants = googleSheetsDtoToRestaurantInfos(data);
Ici tu peux return directement googleSheetsDtoToRestaurantInfos(data); sans le stocker dans une variable intermédiaire

2024-05-10 15:28 UTC, greg-ab commented on src/core/restaurants/getAllRestaurantsSheets.tsx
> +  const restaurants = googleSheetsDtoToRestaurantInfos(data);
Et appeler googleSheetsDtoToRestaurantInfos(restaurantsTable.values)

2024-05-10 15:28 UTC, greg-ab commented on src/core/restaurants/getAllRestaurantsSheets.tsx
> +  googleSheetsAPIKey: string | undefined
Que se passe-t-il quand c'est undefined ? Est-ce un comportement attendu ? normal ?

2024-05-10 15:28 UTC, greg-ab commented on src/core/restaurants/getAllRestaurantsSheets.tsx
> +  data: string[][]
Le nom data est très générique, peux-tu le rendre plus parlant?

2024-05-10 15:28 UTC, greg-ab commented on src/core/restaurants/getAllRestaurantsSheets.tsx
> +          restaurant[key] = row[index];
Ici, tu dois même pouvoir factoriser ça en utilisant une expression ternaire

2024-05-10 15:28 UTC, greg-ab commented on src/core/restaurants/getRandomRestaurantSheets.tsx
> +    key: any,
Ici, plutôt qu'un any, tu peux utiliser un unknown qui t'oblige à vérifier que ton objet est du bon type avant de faire des opérations particulières dessus. Plutôt que de dire "tu peux tout faire", ça revient à dire "tu peux tout faire, tant que tu vérifies que tu peux le faire"

2024-05-10 15:28 UTC, greg-ab commented on src/core/restaurants/getRandomRestaurantSheets.tsx
> +    meatLover: diet === Diet.MEATLOVER ? true : undefined,
Ici `diet === Diet.MEATLOVER` te renvoie un booléen. Tu peux donc utiliser directement cette valeur, sans ternaire (tu as un true/false). Tu auras peut-être besoin d'adapter la logique plus bas, mais ça évite d'introduire du true/undefined qui n'est pas standard pour des assertions ensuite.

2024-05-13 07:52 UTC, corentingst commented on src/app/layout.tsx
> +                  Sheets restaus
C'est l'accès au sheets, avec plus que seulement la liste des restaus. On peut par exemple y laisser des avis

2024-05-13 07:55 UTC, corentingst commented on src/app/page.tsx
> +    useState<RestaurantInfos | undefined>();
Yes on initialise le state en "undefined". Ça peut poser un problème?

2024-05-13 13:57 UTC, Loiklak commented on src/app/restaurant-list/page.tsx
>    const restaurants = await getAllRestaurants();
Si t'as supprimé la page, t'as supprimé le composant, donc il peut plus être importé -> si jamais l'import traîne encore qq part t'aura une erreur

2024-05-13 13:57 UTC, Loiklak commented on src/core/restaurants/getAllRestaurantsSheets.tsx
> +const sheetsColumnsToTechnicalName = {
yes !

2024-05-14 12:56 UTC, merged