Review carousel
Loiklak/keskon-mange-ce-midi pull request #8
Opened 2024-05-17 12:30 UTC by cyprienraf

<div>
    <a href="https://www.loom.com/share/6179554afcd74bd3ae3dc7e0986cc3d7">
      <p>Keskon mange - 17 May 2024 - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/6179554afcd74bd3ae3dc7e0986cc3d7">
      <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/6179554afcd74bd3ae3dc7e0986cc3d7-with-play.gif">
    </a>
  </div>

2024-05-17 12:43 UTC, fontainemartin commented on src/components/RestaurantCard/RestaurantCard.tsx
> +import { ReviewItem } from "./Review/Review";
Harmoniser le nom du composant

2024-05-17 12:45 UTC, fontainemartin commented on src/components/RestaurantCard/Review/Review.tsx
> +  const [numberOfReview, setnumberOfReview] = useState<number>();
setNumberOfReview

2024-05-17 12:56 UTC, fontainemartin commented on src/components/RestaurantCard/Review/Review.tsx
> +  }
Tu peux le définir ailleurs (en haut du fichier ou dans un fichier à part)

2024-05-17 12:58 UTC, fontainemartin commented on src/components/RestaurantCard/Review/Review.tsx
> +    var sliderElem = document.getElementById("slider");
inutilisé

2024-05-17 12:59 UTC, fontainemartin commented on src/components/RestaurantCard/Review/Review.tsx
> +        break;
à extraire dans une méthode

2024-05-17 13:01 UTC, fontainemartin commented on src/components/RestaurantCard/Review/Review.tsx
> +  const [myVariable, setMyVariable] = useState<number>(0);
trouver un nom

2024-05-28 09:06 UTC, Loiklak requested changes

2024-05-28 09:06 UTC, Loiklak commented on src/core/avis/getAllReview.tsx
>    Theodoer: "author",
Je te conseille de mettre les clés dans des constantes pour indiquer ce qu'elles représentent, sinon c'est un peu comme des magic strings ;)

2024-05-28 09:06 UTC, Loiklak commented on src/components/RestaurantCard/Review/ReviewComponent.module.css
> +  flex-shrink: 0;
Bizarre que tu aies besoin de ce style là dans un composant réutilisable, c'est un smell ça devrait plutôt être géré au même endroit que le parent qui met le display flex

2024-05-28 09:06 UTC, Loiklak commented on src/components/RestaurantCard/Review/ReviewComponent.module.css
> +  justify-content: center;
N'a pas d'effet si tu n'es pas dans un display flex ou grid :) tu peux l'enlever

2024-05-28 09:06 UTC, Loiklak commented on src/components/RestaurantCard/Review/ReviewComponent.tsx
> +        href="https://docs.google.com/spreadsheets/d/1B1kD-kZQiJUEYcSmAXom_lY7_JhOLp9UTq0Uf44wNY0/edit#gid=915087104"
Mets le lien dans une constante et isole toutes les constantes dans un fichier séparé, ça permettra de beaucoup mieux identifier la partie "configuration" du code

2024-05-28 09:06 UTC, Loiklak commented on src/components/RestaurantCard/Review/ReviewComponent.tsx
> +};
En plus conventionnel tu devrais plutôt avoir un composant <NoReview /> que tu affiches ici ;) plutôt que la fonction displayNoReview() (au final ça change rien je crois, c'est juste que ton display no review c'est un composant donc autant utiliser la bonne convention :))

2024-05-28 09:06 UTC, Loiklak commented on src/components/RestaurantCard/Review/ReviewComponent.module.css
> +  text-align: left;
Valeur par défaut, t'en n'as pas besoin je pense

2024-05-28 09:06 UTC, Loiklak commented on src/components/RestaurantCard/Review/ReviewComponent.module.css
> +  text-align: left;
Sauf si inherited effetivement

2024-05-28 09:06 UTC, Loiklak commented on src/components/RestaurantCard/Review/ReviewComponent.module.css
> +  text-align: right;
Vu ensemble pas besoin

2024-05-28 09:06 UTC, Loiklak commented on src/components/RestaurantCard/Review/ReviewComponent.tsx
> +export const displayOneReviewComment = (review: ReviewInfos) => {
Pareil ici c'est un composant :)

2024-05-28 09:06 UTC, Loiklak commented on src/components/RestaurantCard/RestaurantCard.tsx
> +            )}
`condition && <ReviewCarousel restaurantName={restaurant?.name} />`

2024-05-28 09:06 UTC, Loiklak commented on src/components/RestaurantCard/Review/ReviewCarousel.module.css
> +  flex-direction: row;
Valeur par défaut pas nécessaire

2024-05-28 09:06 UTC, Loiklak commented on src/components/RestaurantCard/Review/ReviewCarousel.module.css
> +  width: 500px;
A refactor pour utiliser plutôt une grid ou un flex

2024-05-28 09:06 UTC, Loiklak commented on src/components/RestaurantCard/Review/ReviewCarousel.tsx
> +    createTimerChangingCurrentCommentAfterIt();
initCarouselAutoAnimation

Pour qu'on comprenne a quoi ça sert fonctionnellement

2024-05-28 09:06 UTC, Loiklak commented on src/components/RestaurantCard/Review/ReviewCarousel.tsx
> +    var reviewArray: ReviewInfos[] = [];
utiliser const ou let plutôt que var

2024-05-28 09:06 UTC, Loiklak commented on src/components/RestaurantCard/Review/ReviewCarousel.tsx
> +    createTimerChangingCurrentCommentAfterIt();
const myFunc = async () => {
	const reviewArray = await ...
	if (restaurantName) {
		....
	}
}

2024-05-28 09:06 UTC, Loiklak commented on src/components/RestaurantCard/Review/ReviewCarousel.tsx
> +    createTimerChangingCurrentCommentAfterIt();
-> Tout mettre dans une fonction async

2024-05-28 13:38 UTC, merged